esd:
  profiles:
    active: local
  server:
    name: esd-server
    worker_num: 4
    max_conn: 1024
    debug: true
  port:
    mqtt:
      host: 0.0.0.0
      port: 8090
      open_mqtt_protocol: true
      pack_tool: ESD\Plugins\MQTT\MqttPack
      sock_type: 1